export const outArr = [
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_0_0.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_1_8.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_7_7.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_9_2.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_0_1.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_13_1.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_1_6.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_9_9.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_0_2.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_13_4.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_4_3.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_4_4.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_0_3.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_2_4.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_7_1.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_7_2.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_0_4.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_13_6.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_5_4.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_7_5.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_0_5.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_13_8.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_5_3.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_7_6.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_0_6.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_1_3.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_6_3.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_8_9.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_0_7.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_1_5.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_8_5.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_9_7.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_0_8.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_10_3.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_13_3.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_5_6.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_0_9.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_5_1.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_5_2.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_8_6.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_10_0.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_3_8.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_6_0.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_8_0.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_10_1.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_12_4.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_12_9.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_3_1.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_10_2.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_3_3.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_7_4.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_9_6.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_10_4.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_11_2.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_11_3.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_8_2.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_10_5.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_2_2.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_2_3.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_4_5.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_10_6.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_2_6.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_4_8.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_9_5.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_10_7.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_4_6.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_5_7.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_7_8.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_10_8.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_12_3.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_1_7.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_7_3.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_10_9.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_12_2.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_1_9.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_8_3.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_11_0.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_12_5.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_3_9.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_5_5.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_11_1.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_4_9.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_5_8.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_5_9.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_11_4.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_6_4.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_9_0.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_9_8.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_11_5.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_13_2.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_1_0.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_9_4.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_11_6.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_12_6.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_13_7.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_2_8.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_11_7.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_11_8.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_2_7.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_8_7.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_11_9.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_6_9.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_7_0.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_7_9.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_12_0.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_12_1.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_13_5.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_6_1.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_12_7.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_12_8.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_13_0.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_1_1.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_1_2.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_2_5.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_13_9.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_1_4.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_3_4.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_5_0.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_2_0.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_4_7.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_6_5.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_9_3.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_2_1.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_4_0.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_6_6.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_8_8.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_2_9.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_3_2.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_4_2.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_8_4.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_3_0.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_3_7.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_4_1.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_6_2.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_3_5.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_3_6.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_6_7.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_6_8.jpg",
  ],
  [
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_8_1.jpg",
    "d:\\project\\my\\yang-le-xiao\\src\\out\\block_9_1.jpg",
  ],
];
export const logArr = (arr: number[][]) => {
  arr.forEach((item) => {
    console.log(
      item.map((info) => info.toString().padStart(2, "0")).join(" , ")
    );
  });
};

export const fontColor:{[key: number]: string} = {
  0: "#ffffff",
  1: "#ff9999",
  2: "#ffcc99",
  3: "#ffff99",
  4: "#ccff99",
  5: "#99ff99",
  6: "#99ffcc",
  7: "#99ffff",
  8: "#99ccff",
  9: "#9999ff",
  10: "#cc99ff",
  11: "#ff99ff",
  12: "#ff66cc",
  13: "#ff9966",
  14: "#ffcc66",
  15: "#ffff66",
  16: "#ccff66",
  17: "#99ff66",
  18: "#66ff66",
  19: "#66ff99",
  20: "#66ffcc",
  21: "#66ffff",
  22: "#66ccff",
  23: "#6699ff",
  24: "#6666ff",
  25: "#9966ff",
  26: "#cc66ff",
  27: "#ff66ff",
  28: "#ff3399",
  29: "#ff6633",
  30: "#ff9933",
  31: "#ffcc33",
  32: "#ffff33",
  33: "#ccff33",
  34: "#99ff33",
  35: "#66ff33",
  36: "#33ff33",
  37: "#33ff66",
  38: "#33ff99",
  39: "#33ffcc",
  40: "#33ffff",
  41: "#33ccff",
  42: "#3399ff",
  43: "#3366ff",
  44: "#6633ff",
  45: "#9933ff",
  46: "#cc33ff",
  47: "#ff33ff",
  48: "#ff0066",
  49: "#ff3300",
  50: "#ff6600",
  51: "#ff9900",
  52: "#ffcc00",
  53: "#ffff00",
  54: "#ccff00",
  55: "#99ff00",
  56: "#66ff00",
  57: "#33ff00",
  58: "#00ff00",
  59: "#00ff33",
  60: "#00ff66",
  61: "#00ff99",
  62: "#00ffcc",
  63: "#00ffff",
  64: "#00ccff",
  65: "#0099ff",
  66: "#0066ff",
  67: "#0033ff",
  68: "#3300ff",
  69: "#6600ff",
  70: "#9900ff",
};
